assets:
  settings.xml: ashtonhogan/tacinga#settings.xml.asc
  pubring.gpg: ashtonhogan/tacinga#pubring.gpg.asc
  secring.gpg: ashtonhogan/tacinga#secring.gpg.asc
friends:
  - ashtonhogan/tacinga
  - yegor256/rultor
  - jcabi/*
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
  JAVA_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri xcop
architect:
- ashtonhogan
merge:
  script: |
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Ptacinga -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml